// <auto-generated />
namespace ThoughtBubbles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LiaisonentreProjetetRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LiaisonentreProjetetRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201609200736567_Liaison entre Projet et Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
